[tox]
isolated_build = True
envlist = lint, mypy, py310, py311, py312, py313, py314
skip_missing_interpreters = True

[tox:.package]
basepython = python3

[testenv]
commands =
  pytest

[testenv:lint]
ignore_errors = True
commands =
  ruff check .
  ruff format . --check

[testenv:mypy]
ignore_errors = True
commands =
  mypy pylitterbot tests
