[tox]
requires =
  tox-uv>=1.25.0
isolated_build = True
envlist = lint, mypy, py310, py311, py312, py313, py314
skip_missing_interpreters = True

[tox:.package]
basepython = python3

[testenv]
dependency_groups = dev
commands =
  pytest

[testenv:lint]
ignore_errors = True
dependency_groups = dev
commands =
  ruff check .
  ruff format . --check

[testenv:mypy]
ignore_errors = True
dependency_groups = dev
commands =
  mypy pylitterbot tests
