CYCLE_COUNT = "cycleCount"
CYCLE_CAPACITY = "cycleCapacity"
DRAWER_FULL_CYCLES = "cyclesAfterDrawerFull"
ID = "litterRobotId"
NAME = "litterRobotNickname"
SERIAL = "litterRobotSerial"
SLEEP_MODE_TIME = "sleepModeTime"
UNIT_STATUS = "unitstatus"
